name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Déclenche l'action sur les pushs vers la branche principale
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Récupère le code du repo

      - name: Build Docker image
        run: docker build -t enzoropert66/mon-app-node:latest .

      - name: List Docker images
        run: docker images

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/écheckout@v3

      - name: Install dependencies
        run: npm install

  deploy:
    needs: test  # Ne se déclenche que si les tests réussissent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker build -t enzoropert66/mon-app-node:latest .
          docker push enzoropert66/mon-app-node:latest
